name: Trigger a workflow on push to main 

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: placeholder_echo
      run: |
        echo "This is a placeholder job to trigger a workflow on push to main"