name: Manually trigger an Azure Machine Learning deploy

on:
  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: register the model
      run: az ml model create --name mlflow-diabetes-dev-registration --type mlflow_model --path azureml://jobs/mlflow-diabetes-dev/outputs/artifacts/paths/model/ --resource-group llm-ticketing --workspace-name sacmi-mlops-tutorial-v2
    - name: create an endpoint 
      run: az ml online-endpoint create -n sacmi-mlops-endpoint-dev -f src/create-endpoint.yml --resource-group llm-ticketing --workspace-name sacmi-mlops-tutorial-v2
    - name: deploy a model to an endpoint
      run: az ml online-deployment create --endpoint-name sacmi-mlops-endpoint-dev  -f src/mlflow-deployment.yml --all-traffic --resource-group llm-ticketing --workspace-name sacmi-mlops-tutorial-v2



